apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sfp-portal
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api
          image: registry.digitalocean.com/sfp-portal/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: DB_SSL
              value: "true"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_EXPIRES_IN
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SENDGRID_API_KEY
            - name: SENDGRID_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SENDGRID_FROM_EMAIL
            - name: DO_SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-credentials
                  key: DO_SPACES_KEY
            - name: DO_SPACES_SECRET
              valueFrom:
                secretKeyRef:
                  name: spaces-credentials
                  key: DO_SPACES_SECRET
            - name: DO_SPACES_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DO_SPACES_ENDPOINT
            - name: DO_SPACES_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DO_SPACES_BUCKET
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_URL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: sfp-portal
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 5000
      targetPort: 5000
      name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: sfp-portal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
