export const mockUsers = [
  {
    id: "1",
    email: "adopter@example.com",
    password: "password123",
    name: "Adopter User",
    role: ["adopter"],
  },
  {
    id: "2",
    email: "foster@example.com",
    password: "password123",
    name: "Foster User",
    role: ["foster"],
  },
  {
    id: "3",
    email: "superfoster@example.com",
    password: "password123",
    name: "Super Foster User",
    role: ["foster", "super foster"],
  },
  {
    id: "4",
    email: "interviewer@example.com",
    password: "password123",
    name: "Interviewer User",
    role: ["interviewer"],
  },
  {
    id: "5",
    email: "admin@example.com",
    password: "password123",
    name: "Admin User",
    role: ["admin"],
  },
];

export const mockAnimals = [
  {
    id: "1",
    uniqueId: "SFP-123",
    name: "Max",
    species: "Dog",
    breed: "Golden Retriever",
    age: "2 years",
    sex: "Male",
    size: "Large",
    color: "Golden",
    description:
      "Friendly and energetic Golden Retriever who loves to play fetch.",
    personality: ["Friendly", "Energetic", "Loyal"],
    imageUrls: [],
    vaccinated: true,
    neutered: true,
    goodWith: { children: true, dogs: true, cats: true },
    location: "PetSmart Downtown",
    adoptionFee: 250,
    intakeDate: "2025-10-15",
    postedDate: "2025-11-01",
    status: "published",
    microchipNumber: "981020012345678",
    medicalHistory: "Up to date on vaccinations.",
    behaviorNotes: "Well-trained.",
    intakeSource: "Stray",
    internalNotes: "Needs daily exercise.",
  },
  {
    id: "2",
    uniqueId: "SFP-124",
    name: "Luna",
    species: "Cat",
    breed: "Siamese",
    age: "1 year",
    sex: "Female",
    size: "Small",
    color: "Seal Point",
    description: "Graceful Siamese cat with striking blue eyes.",
    personality: ["Affectionate", "Playful", "Independent"],
    imageUrls: [],
    vaccinated: true,
    neutered: true,
    goodWith: { children: true, dogs: false, cats: true },
    location: "PetValu Uptown",
    adoptionFee: 150,
    intakeDate: "2025-10-20",
    postedDate: "2025-11-05",
    status: "published",
    microchipNumber: "981020012345679",
    medicalHistory: "Spayed.",
    behaviorNotes: "Vocal.",
    intakeSource: "Owner surrender",
    internalNotes: "Prefers quiet home.",
  },
];
