import sequelize from "../config/database.js";
import { Animal, Volunteer } from "../models/index.js";

async function seedAnimals() {
  try {
    await sequelize.authenticate();

    const foster = await Volunteer.findOne({ where: { role: "foster" } });

    if (!foster) {
      console.error("❌ No foster found — seed volunteers first!");
      process.exit(1);
    }

    const animals = [
      // ------------------- CATS -------------------
      {
        unique_id: "SFP-001",
        name: "Mochi",
        species: "cat",
        breed: "Domestic Shorthair",
        age: "2 years",
        sex: "Female",
        size: "Small",
        color: "Calico",
        description: "A sweet gentle girl who loves sunbathing and soft blankets.",
        personality: ["calm", "gentle"],
        image_urls: ["https://placekitten.com/400/400"],
        vaccinated: true,
        neutered: true,
        good_with_children: true,
        good_with_dogs: false,
        good_with_cats: true,
        location: "Scarborough, ON",
        adoption_fee: 200,
        intake_date: "2024-11-22",
        posted_date: "2024-12-01",
        status: "published",
        volunteer_id: foster.id,
      },
      {
        unique_id: "SFP-002",
        name: "Pumpkin",
        species: "cat",
        breed: "Tabby",
        age: "4 months",
        sex: "Male",
        size: "Small",
        color: "Orange Tabby",
        description: "Playful kitten who loves toy mice and tunnels.",
        personality: ["playful", "curious"],
        image_urls: ["https://placekitten.com/410/400"],
        vaccinated: true,
        neutered: false,
        good_with_children: true,
        good_with_dogs: true,
        good_with_cats: true,
        location: "Markham, ON",
        adoption_fee: 250,
        intake_date: "2025-01-05",
        posted_date: "2025-01-10",
        status: "published",
        volunteer_id: foster.id,
      },
      {
        unique_id: "SFP-003",
        name: "Snowball",
        species: "cat",
        breed: "Persian",
        age: "5 years",
        sex: "Female",
        size: "Medium",
        color: "White",
        description: "Calm and elegant, prefers quiet homes.",
        personality: ["calm"],
        image_urls: ["https://placekitten.com/401/400"],
        vaccinated: true,
        neutered: true,
        good_with_children: false,
        good_with_dogs: false,
        good_with_cats: false,
        location: "Richmond Hill, ON",
        adoption_fee: 150,
        intake_date: "2024-10-13",
        posted_date: "2024-10-20",
        status: "published",
        volunteer_id: foster.id,
      },

      // ------------------- DOGS -------------------
      {
        unique_id: "SFP-004",
        name: "Benny",
        species: "dog",
        breed: "Golden Retriever",
        age: "1 year",
        sex: "Male",
        size: "Large",
        color: "Golden",
        description: "Energetic boy who loves fetch and belly rubs.",
        personality: ["energetic", "friendly"],
        image_urls: ["https://placedog.net/500/400"],
        vaccinated: true,
        neutered: false,
        good_with_children: true,
        good_with_dogs: true,
        good_with_cats: false,
        location: "Mississauga, ON",
        adoption_fee: 350,
        intake_date: "2024-11-20",
        posted_date: "2024-12-01",
        status: "published",
        volunteer_id: foster.id,
      },
      {
        unique_id: "SFP-005",
        name: "Nala",
        species: "dog",
        breed: "Shiba Inu",
        age: "3 years",
        sex: "Female",
        size: "Medium",
        color: "Cream",
        description: "Independent but affectionate once she trusts you.",
        personality: ["independent"],
        image_urls: ["https://placedog.net/501/400"],
        vaccinated: true,
        neutered: true,
        good_with_children: false,
        good_with_dogs: false,
        good_with_cats: true,
        location: "Toronto, ON",
        adoption_fee: 400,
        intake_date: "2025-01-02",
        posted_date: "2025-01-09",
        status: "published",
        volunteer_id: foster.id,
      },
      {
        unique_id: "SFP-006",
        name: "Toby",
        species: "dog",
        breed: "Corgi",
        age: "2 years",
        sex: "Male",
        size: "Medium",
        color: "Tan & White",
        description: "Short legs, big personality! Loves food.",
        personality: ["funny", "food-motivated"],
        image_urls: ["https://placedog.net/502/400"],
        vaccinated: true,
        neutered: true,
        good_with_children: true,
        good_with_dogs: true,
        good_with_cats: true,
        location: "North York, ON",
        adoption_fee: 300,
        intake_date: "2024-12-15",
        posted_date: "2024-12-22",
        status: "published",
        volunteer_id: foster.id,
      },

      // ------------------- SMALL ANIMALS -------------------
      {
        unique_id: "SFP-007",
        name: "Cinnamon",
        species: "rabbit",
        breed: "Holland Lop",
        age: "8 months",
        sex: "Female",
        size: "Small",
        color: "Chestnut",
        description: "Loves gentle pets and parsley snacks.",
        personality: ["gentle"],
        image_urls: ["https://placekitten.com/420/400"], // placeholder bunny
        vaccinated: false,
        neutered: false,
        good_with_children: true,
        good_with_dogs: false,
        good_with_cats: true,
        location: "Etobicoke, ON",
        adoption_fee: 80,
        intake_date: "2024-09-12",
        posted_date: "2024-09-15",
        status: "published",
        volunteer_id: foster.id,
      },
      {
        unique_id: "SFP-008",
        name: "Mallow",
        species: "guinea pig",
        breed: "American",
        age: "1 year",
        sex: "Male",
        size: "Small",
        color: "Brown & White",
        description: "Chatty boy who loves lettuce and tunnels.",
        personality: ["vocal"],
        image_urls: ["https://placekitten.com/421/400"], // placeholder
        vaccinated: false,
        neutered: false,
        good_with_children: true,
        good_with_dogs: false,
        good_with_cats: true,
        location: "Vaughan, ON",
        adoption_fee: 40,
        intake_date: "2024-11-01",
        posted_date: "2024-11-05",
        status: "published",
        volunteer_id: foster.id,
      },

      // ------------------- PETSMART PARTNERS -------------------
      {
        unique_id: "SFP-009",
        name: "Luna",
        species: "cat",
        breed: "DSH",
        age: "3 years",
        sex: "Female",
        size: "Small",
        color: "Black",
        description: "Currently staying at PetSmart (Markham).",
        personality: ["quiet"],
        image_urls: ["https://placekitten.com/413/400"],
        vaccinated: true,
        neutered: true,
        good_with_children: true,
        good_with_dogs: false,
        good_with_cats: true,
        location: "PetSmart Markham",
        adoption_fee: 150,
        intake_date: "2024-12-01",
        posted_date: "2024-12-05",
        status: "published",
        volunteer_id: foster.id,
      },

      // ------------------- PETVALU PARTNERS -------------------
      {
        unique_id: "SFP-010",
        name: "Olive",
        species: "cat",
        breed: "DSH",
        age: "1 year",
        sex: "Female",
        size: "Small",
        color: "Black & White",
        description: "Friendly girl located at PetValu Richmond Hill.",
        personality: ["friendly"],
        image_urls: ["https://placekitten.com/414/400"],
        vaccinated: true,
        neutered: true,
        good_with_children: true,
        good_with_dogs: true,
        good_with_cats: true,
        location: "PetValu Richmond Hill",
        adoption_fee: 180,
        intake_date: "2024-12-14",
        posted_date: "2024-12-18",
        status: "published",
        volunteer_id: foster.id,
      }
    ];

    for (const a of animals) {
      await Animal.upsert(a);
    }

    console.log("✓ 12 animals seeded successfully");
    process.exit(0);
  } catch (err) {
    console.error("❌ Error seeding animals:", err);
    process.exit(1);
  }
}

seedAnimals();
